spring:
  datasource:
    url: jdbc:postgresql://pizzeria-db.cvo8ivykvtbt.eu-north-1.rds.amazonaws.com:5432/pizzeria_db
    username: postgres
    password: Pizzeria
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
