spring:
  datasource:
    url: jdbc:postgresql://pizzeria-db.cvo8ivykvtbt.eu-north-1.rds.amazonaws.com:5432/pizzeria_db
    username: postgres
    password: Pizzeria
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: ostapnote2@gmail.com
    password:
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    cache: false # for development, set to true in production
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    suffix: .ftl
